quotes/quotes_test_project/quotes/urls.py
from django.urls import path
from . import views

app_name = 'quotes'

urlpatterns = [
    path(
        '',
        views.get_random_quote,
        name='get_random_quote'
    ),
    path(
        'quotes/create/',
        views.create_quote,
        name='create_quote'
    ),
    path(
        'quotes/edit/<int:quote_id>/',
        views.edit_quote,
        name='edit_quote'
    ),
    path(
        'quotes/delete/<int:quote_id>/',
        views.delete_quote,
        name='delete_quote'
    ),
    path(
        'quotes/like/<int:quote_id>/',
        views.like_quote,
        name='like_quote'
    ),
    path(
        'quotes/dislike/<int:quote_id>/',
        views.dislike_quote,
        name='dislike_quote'
    ),
    path(
        'quotes/manage/',
        views.manage_quotes,
        name='manage_quotes'
    ),
    path(
        'quotes/top_quotes/',
        views.get_top_quotes,
        name='get_top_quotes'
    )
]

quotes/quotes_test_project/quotes_test_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('sources/', include('sources.urls')),
]

quotes/quotes_test_project/sources/urls.py
from django.urls import path

from . import views

app_name = 'sources'

urlpatterns = [
    path(
        'create/',
        views.create_source,
        name='create_source'
    ),
    path(
        'edit/<int:source_id>/',
        views.edit_source,
        name='edit_source'
    ),
    path(
        'delete/<int:source_id>/',
        views.delete_source,
        name='delete_source'
        ),
    path(
        'manage/',
        views.manage_sources,
        name='manage_sources'
    ),
]

quotes/quotes_test_project/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Цитатник</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'quotes:get_random_quote'%}">Цитатник Кирилла Терминасова</a>
            <div class="navbar-nav">
                <a class="nav-link" href="{% url 'quotes:get_random_quote'%}">Случайная цитата</a>
                <a class="nav-link" href="{% url 'quotes:manage_quotes'%}">Управление цитатами</a>
                <a class="nav-link" href="{% url 'sources:manage_sources'%}">Управление источниками</a> 
                <a class="nav-link" href="{% url 'quotes:get_top_quotes'%}">Топ цитат</a> 
            </div>
        </div>
    </nav>

    <div class="container mt-4">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
        
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>